"""
End-to-end smoke test: constructs the REAL MainWindow (offscreen), feeds
it packets generated by the REAL SimulationEngine's synthetic flight
profile (the same one behind the "Start Synthetic" button), sets a
guidance target, arms guidance, and watches the LandingController /
GuidanceDashboard react as the flight passes through DESCENT_SECONDARY
(state "6") -- exactly the phase precision landing should be active in.

Run:
    QT_QPA_PLATFORM=offscreen python3 e2e_guidance_test.py
"""
import sys

from PyQt5 import QtWebEngineWidgets  # noqa: F401  (import order requirement)
from PyQt5 import QtWidgets

app = QtWidgets.QApplication(sys.argv)

from ui.main_window import MainWindow
from simulation.simulation_engine import SimulationEngine

win = MainWindow()

# Patch serial_link.send_command so we can see every command the
# LandingController transmits without needing real hardware.
sent_commands = []


class FakeSerialLink:
    def is_connected(self):
        return True

    def send_command(self, cmd):
        sent_commands.append(cmd)


win.serial_link = FakeSerialLink()

# Drive the real synthetic simulation engine by hand (bypassing its
# QTimer) so this runs instantly instead of waiting 82 real seconds.
engine = SimulationEngine()
engine.mode = "synthetic"
engine.packet_count = 0
engine.synthetic_time = 0.0
engine.altitude = 0.0
engine.velocity = 0.0
engine.synthetic_state = "LAUNCH_PAD"

target_set = False
seen_states = set()

for step in range(90):
    line = engine._generate_synthetic_packet()
    if line is None:
        break  # mission complete (impact)

    win._inject_packet(line)

    state = win.landing_controller  # just to keep reference warm
    fields = line.split(",")
    flight_state = fields[18]  # FLIGHT_STATE is field index 18 (0-based)
    seen_states.add(flight_state)

    # Once we have a GPS-derived reference point (first packet with a
    # fix) and we're not yet armed, set a target ~15m east of the
    # reference-ish point and arm guidance -- same as pressing
    # "SET TARGET" in the Guidance tab.
    if win._guidance_reference_set and not target_set:
        lat = win.landing_controller.origin  # local coords already set
        # Use a target offset from the CURRENT gps fix so a cross-track
        # error actually develops as the descent continues.
        cur_lat = float(fields[8])
        cur_lon = float(fields[9])
        target_lat = cur_lat
        target_lon = cur_lon + 0.0003  # ~30m east at this latitude
        win.guidance_dashboard.target_lat_input.setText(str(target_lat))
        win.guidance_dashboard.target_lon_input.setText(str(target_lon))
        win._on_set_guidance_target()
        target_set = True
        print(f"[step {step}] target armed at ({target_lat}, {target_lon})")

    if step % 10 == 0 or flight_state == "6":
        print(
            f"[step {step:2d}] state={flight_state} alt={fields[3]:>7} "
            f"lat={fields[8]} lon={fields[9]} "
            f"armed={win.landing_controller.armed} "
            f"cmd={win.landing_controller.current_command}"
        )

print("\nFlight states seen:", sorted(seen_states))
print("Commands actually sent over (fake) serial:", sent_commands)
print("\nGuidance dashboard final reading:")
print("  distance:", win.guidance_dashboard.val_distance.text())
print("  xtrack:  ", win.guidance_dashboard.val_xtrack.text())
print("  command: ", win.guidance_dashboard.val_command.text())
print("  status:  ", win.guidance_dashboard.val_status.text())
print("  wind:    ", win.guidance_dashboard.val_wind_speed.text(),
      win.guidance_dashboard.val_wind_dir.text())

assert "6" in seen_states, "synthetic profile never reached DESCENT_SECONDARY"
assert len(sent_commands) > 0, "controller never transmitted a command"
print("\nE2E SMOKE TEST PASSED")
